name: rich_stdout
description: A library that provides functions for modifying the console output in Dart. It currently supports colouring, bolding, italicising, and underlining text. It also supports hiding and showing the cursor, and moving the cursor to an arbitrary position on the screen.
version: 1.0.4
repository: https://github.com/SirToby-Gore/dart-rich-stdout

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
